/* ═══════════════════════════════════════════
   startupData.ts — M-life 开场初始化数据
   类似 koyoko-start-01.yaml 模式
   独立模式下读取此文件初始化所有 Pinia Store
   ═══════════════════════════════════════════ */

export const STARTUP_DATA = {
  context: {
    rii_story: '手机屏幕亮了一下。\n\n2025年9月15号，周一，晚上十点。我把车停进地下车库。今天的商单拍摄比预想顺利，提前收工。从电梯上来，大平层里安静得只剩下中央空调的嗡嗡声。\n\n我把钥匙丢在玄关柜上，没开大灯，只有客厅落地窗透进来的城市光。微信工作群99+，没兴趣看。微博热搜划了两下，没意思。\n\n手指停在那個黑色图标上——M-life。\n\n---\n\n画面加载。熟悉的暗色界面。底部五个Tab亮着第一个。首页信息流刷新出来几条新动态。\n\n我靠在沙发上，拇指在屏幕上慢慢滑动。有人发了张夜宵图，配文是「深夜了，有人一起恰夜宵吗」。下面已经多了几百个赞。我随手点了个赞，继续往下滑。',
    current_time: '9月15日 22:10',
    map_position: {
      area_id: 'virtual',
      facility_id: 'mlife_app',
    },
  },

  user: {
    account: '夜风中的猫',
    balance: 37250,
    exp: '1250/6000',
    level: 'Lv3',
    vip: '黄金',
    signin: '未签',
    signinStreak: 12,
    likes: 342,
    fans: 87,
    following: 156,
    matchToday: '1/2',
    postToday: '3/8',
    recruitActive: 2,
    recruitApplied: 5,
    unboxed: ['小甜心021', '暗夜玫瑰'],
  },

  social: {
    posts: [
      {
        nick: '深夜食堂',
        level: 'Lv4',
        vip: '黑金',
        avatar: '🍜',
        time: '23:15',
        section: '闲聊灌水',
        body: '深夜了 有人一起恰夜宵吗 我请客 前提是陪我聊到天亮',
        image: '一锅热气腾腾的麻辣烫，红油浮面，配料丰富，看得出是常吃的那家店的招牌',
        paywall: '无',
        likes: 847,
        comments: 234,
        shares: 56,
        hot1: '吃货小萌: 啊啊啊这家超好吃！上次吃完拉了两天肚子但还是想去！',
        hot2: '夜猫子: 下次可以叫上我吗 我出酒',
      },
      {
        nick: '小雨转晴',
        level: 'Lv2',
        vip: '白银',
        avatar: '🌂',
        time: '22:50',
        section: '福利自拍',
        body: '今天淋了点雨 换了套新买的睡衣 感觉还不错',
        image: '一位少女穿着白色吊带睡裙，微微湿漉的长发披散在肩头，睡裙的吊带有一侧滑落，露出白皙的肩膀和锁骨线条',
        paywall: '需10M币解锁',
        likes: 1256,
        comments: 389,
        shares: 128,
      },
      {
        nick: '茶里茶气',
        level: 'Lv3',
        vip: '黄金',
        avatar: '🍵',
        time: '21:30',
        section: '女神夜话',
        body: '来投稿一下今天的date对象。见面之前聊得挺好 感觉人挺绅士的 结果吃到一半开始跟我聊前任 还问我是不是第一次date 下头 真的下头 这种人为啥还没被平台封杀',
        image: '无',
        paywall: '无',
        likes: 2341,
        comments: 567,
        shares: 89,
        hot1: '感情分析师: 经典的date聊前任红牌行为，姐妹跑得好！',
        hot2: '吃瓜群众: 求id避雷 私我私我',
        hot3: '老司机: 这种人多的是 习惯就好 关键看体力',
      },
      {
        nick: '摄影师阿Ken',
        level: 'Lv5',
        vip: '黑金',
        avatar: '📷',
        time: '20:00',
        section: '资源分享',
        body: '新到一批私房写真套图 日系小清新风格 全彩高清 无水印 老规矩评论区留邮',
        title: '【写真】夏の記憶·第一弹',
        fileSize: '2.4GB',
        fileFormat: 'ZIP/JPEG',
        price: '免费',
        likes: 3456,
        comments: 892,
        downloads: 1234,
      },
    ],
    matches: [
      {
        nick: '甜甜圈公主',
        level: 'Lv3',
        vip: '黄金',
        age: '22',
        dist: '1.2km',
        active: '刚刚活跃',
        avatar: '🍩',
        tags: '美食,逛街,摄影,看电影',
        bio: '周末喜欢去探店 最近迷上了手冲咖啡 想找人一起打卡新开的甜品店',
      },
      {
        nick: '夜跑达人',
        level: 'Lv2',
        vip: '白银',
        age: '24',
        dist: '3.5km',
        active: '5分钟前',
        avatar: '🏃',
        tags: '运动,户外,音乐,阅读',
        bio: '每天晚上10点固定夜跑5km 跑完回来洗个澡听听音乐 简单但充实的一天',
      },
    ],
    matchDetail: {
      nickname: '甜甜圈公主',
      vip: '黄金',
      age: '22',
      distance: '1.2km',
      active: '刚刚活跃',
      level: 'Lv3',
      registered: '注册1年',
      purpose: '认真交友',
      bio: '周末喜欢去探店 最近迷上了手冲咖啡 想找人一起打卡新开的甜品店。\n平时工作是平面设计师，所以对审美比较有要求。\n不喜欢太急的人，觉得感情要慢慢来。',
      tags: '美食,逛街,摄影,看电影',
      bodyType: '匀称偏瘦 163cm',
      height: '163cm',
      face: '清秀耐看型，笑起来有梨涡',
      features: '喜欢穿连衣裙，身上总有淡淡的果香味',
      dailyStyle: '日系森女风，偏爱米色和白色系',
      dateStyle: '正式约会会穿小黑裙配红唇',
      photo: '一张在咖啡馆拍的照片，微微侧身，长发披肩，手里拿着一杯拿铁，笑起来露出两颗小虎牙',
    },
    liveList: [
      {
        nick: '甜甜Music♪',
        level: 'Lv4',
        avatar: '🎤',
        viewers: 1256,
        title: '今晚来点R&B 点点歌呗~',
        status: '正在直播',
        preview: '穿着宽松的白色卫衣，戴着一副大耳机，正在调试麦克风，背景是挂满彩色灯串的房间',
      },
      {
        nick: '健身教练小刘',
        level: 'Lv3',
        avatar: '💪',
        viewers: 834,
        title: '夜练专场 跟练一小时燃脂',
        status: '正在直播',
        preview: '穿着黑色背心和运动短裤，正在做俯卧撑，汗水浸湿了后背，腹肌线条随着动作起伏',
      },
      {
        nick: '画画的小鱼',
        level: 'Lv2',
        avatar: '🎨',
        viewers: 267,
        title: '摸鱼画画 今日画一条美人鱼~',
        status: '即将开播',
        preview: '',
      },
    ],
    liveRoom: {
      nick: '甜甜Music♪',
      level: 'Lv4',
      avatar: '🎤',
      viewers: 1256,
      title: '今晚来点R&B 点点歌呗~',
      status: '正在直播',
      content: '🎵 舒缓的R&B旋律从音响中流淌出来。主播跟着节奏轻轻晃动身体，偶尔闭眼沉浸在音乐中。\n\n「谢谢『夜风中的猫』送的星空礼物~哇，这个特效好漂亮！想听什么歌？给你唱首《小幸运》好不好？」\n\n直播间弹幕快速滚动着。「好听！」「再来一首」「主播看我！」「求微信！！」',
      danmaku: [
        { name: '夜风中的猫', text: '唱得不错 送你个星空' },
        { name: '寂寞的单身汉', text: '主播有男朋友吗？？' },
        { name: '音乐爱好者', text: '这首的转音处理得真棒' },
        { name: '弹幕机器', text: '主播好美prprpr' },
        { name: '夜风中的猫', text: '再来一首慢一点的' },
      ],
      gifts: ['星空礼物×1（来自夜风中的猫）', '荧光棒×99（来自音乐爱好者）', '玫瑰×10（来自寂寞的单身汉）'],
    },
    selfie: [
      {
        nick: '小雨转晴',
        level: 'Lv2',
        vip: '白银',
        avatar: '🌂',
        time: '22:50',
        caption: '今天淋了点雨 换了套新买的睡衣',
        image: '少女穿着白色吊带睡裙，湿漉漉的长发，滑落的吊带露出白皙的肩膀和锁骨',
        paywall: '需10M币解锁',
        likes: 1256, comments: 389, shares: 128,
      },
    ],
    chatPosts: [
      {
        nick: '深夜食堂',
        level: 'Lv4',
        vip: '黑金',
        avatar: '🍜',
        time: '23:15',
        body: '深夜了 有人一起恰夜宵吗 我请客 前提是陪我聊到天亮',
        poll: '选一个！烤肉:45%,火锅:30%,烧烤:20%,麻辣烫:5%,参与人数:234',
        likes: 847, comments: 234, shares: 56,
        hot1: '吃货小萌: 选火锅！！我投火锅一票！',
        hot2: '肉食动物: 烤肉不解释 深夜只配吃烤肉',
      },
    ],
    resource: [
      {
        nick: '摄影师阿Ken',
        level: 'Lv5',
        vip: '黑金',
        avatar: '📷',
        time: '20:00',
        title: '【写真】夏の記憶·第一弹',
        desc: '日系小清新私房写真套图，全彩高清无水印',
        fileSize: '2.4GB',
        fileFormat: 'ZIP/JPEG',
        price: '免费',
        likes: 3456, comments: 892, downloads: 1234,
      },
    ],
    goddess: [
      {
        codename: '夜话女孩#0712',
        expTime: '昨晚',
        time: '23:30-02:00',
        objectName: '金融男·J先生',
        objectBody: '183cm 经常健身 有腹肌 出手大方',
        looks: '8',
        hygiene: '9',
        place: '铜锣湾某高层公寓',
        vibe: '装修很有品味，落地窗外是维港夜景，他开了瓶红酒气氛很好',
        foreplayDuration: '约20分钟',
        foreplaySkill: '8',
        foreplayDetail: '很温柔，从脖子一路亲下来，到位。手指进去的时候有点急但力度刚好',
        sexDuration: '约30分钟',
        sexSkill: '7',
        sexDetail: '换了三个体位，最喜欢后入因为可以抓着他的腹肌。他体力不错但有点太注重表现了',
        afterAttitude: '事后抱着聊了很久，没有急着走。还点了夜宵外卖，挺贴心的',
        afterOvernight: '是',
        score: '8',
        summary: '除了稍微有点爱显摆之外，整体体验很好。可以再约',
        likes: 234, comments: 67, feels: 89,
        tags: '腹肌控,温柔型,出手大方,夜景好评,可以复约',
      },
    ],
  },

  dm: {
    contacts: [
      {
        id: 'rina_night',
        nick: '梨奈酱',
        level: 'Lv2',
        avatar: '🌸',
        lastMsg: '店长大人~今天的关东煮还有剩的吗…？',
        lastTime: '22:45',
        unread: 2,
        messages: [
          { role: 'incoming', text: '店长大人~今天的关东煮还有剩的吗…？', time: '22:45', status: '已读' },
          { role: 'incoming', text: '我今天又迟到了真的对不起嘛…下班请你吃宵夜？', time: '22:46', context: '语气带着撒娇和讨好的意味', status: '已读' },
          { role: 'outgoing', text: '热狗还有两个。再迟到就扣工资。', time: '22:47', status: '已读' },
        ],
      },
      {
        id: 'match01',
        nick: '甜甜圈公主',
        level: 'Lv3',
        avatar: '🍩',
        lastMsg: '明天那家新开的甜品店要不要一起去？☺️',
        lastTime: '20:15',
        unread: 1,
        messages: [
          { role: 'incoming', text: '明天那家新开的甜品店要不要一起去？☺️', time: '20:15', context: '小心试探的语气，带着期待', status: '已读' },
        ],
      },
      {
        id: 'shino_gamer',
        nick: '汐奈',
        level: 'Lv1',
        avatar: '🎮',
        lastMsg: '喂 给我转点钱 我要抽卡！！',
        lastTime: '19:30',
        unread: 0,
        messages: [
          { role: 'incoming', text: '喂 给我转点钱 我要抽卡！！', time: '19:30', status: '已读' },
          { role: 'outgoing', text: '没钱。去找个工作。', time: '19:31', status: '已读' },
          { role: 'incoming', text: '小气鬼！！我明天就去直播赚大钱！', time: '19:32', context: '恼羞成怒的口吻', status: '已读' },
        ],
      },
    ],
    unboxCache: {
      '小甜心021': { nick: '小甜心021', age: '21', occupation: '大学生', height: '162cm', figure: '匀称', drive: '正常偏强', tags: '可爱型,学生妹,紧', preference: '温柔型,喜欢前戏', rating: '4星' },
      '暗夜玫瑰': { nick: '暗夜玫瑰', age: '27', occupation: 'OL', height: '168cm', figure: '丰满', drive: '强', tags: '御姐,主动,经验丰富', preference: '主导型,喜欢挑战', rating: '5星' },
    },
    unboxedIds: ['小甜心021', '暗夜玫瑰'],
    badges: { dm: 3, match: 1 },
  },

  recruit: {
    list: [
      {
        code: 'NGW#4721',
        credit: '4.8',
        type: '📍 单人约会',
        typeIcon: '📍',
        title: '周末艺术展+下午茶 找一个有品味的你',
        budget: '50000 M币',
        tags: '艺术,看展,下午茶,聊天',
        status: '招募中',
        applicants: 3,
        location: '上海·外滩',
        time: '本周六 14:00',
      },
      {
        code: 'ACE#8912',
        credit: '4.5',
        type: '🎭 角色扮演',
        typeIcon: '🎭',
        title: '长期固定CP 古风/现代皆可',
        budget: '80000 M币',
        tags: '古风,现代,剧情向,长期',
        status: '招募中',
        applicants: 7,
        location: '线上',
        time: '协商',
      },
      {
        code: 'VIP#3301',
        credit: '4.9',
        type: '👥 多人聚会',
        typeIcon: '👥',
        title: '私人生日派对 招募4位玩伴',
        budget: '200000 M币/人',
        tags: '派对,高端,私密,社交',
        status: '已锁定',
        applicants: 1,
        location: '深圳·南山',
        time: '下周五 20:00',
      },
    ],
    detail: {
      code: 'NGW#4721',
      credit: '4.8',
      type: '📍 单人约会',
      typeIcon: '📍',
      title: '周末艺术展+下午茶 找一个有品味的你',
      budget: '50000 M币',
      location: '上海·外滩',
      time: '本周六 14:00 - 17:00',
      tags: '艺术,看展,下午茶,聊天',
      status: '招募中',
      applicants: 3,
      description: '外滩某画廊周末有个当代艺术展，想去看看。结束后附近有家不错的下午茶店，如果聊得来可以一起吃个晚饭。\n希望你是一个对艺术有一定了解或者感兴趣的人，不需要多专业，能聊就行。\n不接受太着急的人，慢慢来。',
      requirements: '20-30岁，女性，身材匀称，穿着得体，不喷太浓的香水',
    },
    manage: [
      {
        typeIcon: '📍',
        title: '周末艺术展+下午茶',
        type: '单人约会',
        status: '招募中',
        time: '本周六',
        budget: '50000 M币',
        applicants: 3,
      },
      {
        typeIcon: '🎭',
        title: '长期固定CP 古风/现代',
        type: '角色扮演',
        status: '招募中',
        time: '长期',
        budget: '80000 M币',
        applicants: 7,
      },
    ],
  },
}

export type StartupData = typeof STARTUP_DATA
